//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Research.DynamicDataDisplay.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Research.DynamicDataDisplay.Strings.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array height should be positive..
        /// </summary>
        public static string ArrayHeightShouldBePositive {
            get {
                return ResourceManager.GetString("ArrayHeightShouldBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array width should be positive..
        /// </summary>
        public static string ArrayWidthShouldBePositive {
            get {
                return ResourceManager.GetString("ArrayWidthShouldBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion failed..
        /// </summary>
        public static string AssertionFailed {
            get {
                return ResourceManager.GetString("AssertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion failed - search for reasons in code, that is calling method, where this assertion is performed.
        /// </summary>
        public static string AssertionFailedSearch {
            get {
                return ResourceManager.GetString("AssertionFailedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine desired type of output image by given file extension..
        /// </summary>
        public static string CannotDetermineImageTypeByExtension {
            get {
                return ResourceManager.GetString("CannotDetermineImageTypeByExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get last element of empty list..
        /// </summary>
        public static string CannotGetLastElement {
            get {
                return ResourceManager.GetString("CannotGetLastElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot modify empty DataRect..
        /// </summary>
        public static string CannotModifyEmptyDataRect {
            get {
                return ResourceManager.GetString("CannotModifyEmptyDataRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom base cannot be Double.NaN..
        /// </summary>
        public static string CustomBaseTicksProviderBaseIsNaN {
            get {
                return ResourceManager.GetString("CustomBaseTicksProviderBaseIsNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom base should be greater that 1.0..
        /// </summary>
        public static string CustomBaseTicksProviderBaseIsTooSmall {
            get {
                return ResourceManager.GetString("CustomBaseTicksProviderBaseIsTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataRect&apos;s size cannot be negative..
        /// </summary>
        public static string DataRectSizeCannotBeNegative {
            get {
                return ResourceManager.GetString("DataRectSizeCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each transform in transforms should not be null..
        /// </summary>
        public static string EachTransformShouldNotBeNull {
            get {
                return ResourceManager.GetString("EachTransformShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension cannot be null or empty..
        /// </summary>
        public static string ExtensionCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ExtensionCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filepath cannot be null or empty..
        /// </summary>
        public static string FilePathCannotbeNullOrEmpty {
            get {
                return ResourceManager.GetString("FilePathCannotbeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenericLocationalProvider doesn&apos;t have all necessary properties set..
        /// </summary>
        public static string GenericLocationalProviderInvalidState {
            get {
                return ResourceManager.GetString("GenericLocationalProviderInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal axis can be placed only from bottom or top..
        /// </summary>
        public static string HorizontalAxisCannotBeVertical {
            get {
                return ResourceManager.GetString("HorizontalAxisCannotBeVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis placement is incorrect..
        /// </summary>
        public static string InvalidAxisPlacement {
            get {
                return ResourceManager.GetString("InvalidAxisPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can hold axis only of {1} type..
        /// </summary>
        public static string InvalidGenericAxis {
            get {
                return ResourceManager.GetString("InvalidGenericAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal type of GenericPlotter is invalid..
        /// </summary>
        public static string InvalidGenericPlotterHorizontalType {
            get {
                return ResourceManager.GetString("InvalidGenericPlotterHorizontalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical type of GenericPlotter is invalid..
        /// </summary>
        public static string InvalidGenericPlotterVerticalType {
            get {
                return ResourceManager.GetString("InvalidGenericPlotterVerticalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value of child&apos;s parent plotter - it should be equal to plotter that child is added to..
        /// </summary>
        public static string InvalidParentPlotterValue {
            get {
                return ResourceManager.GetString("InvalidParentPlotterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value of child&apos;s parent plotter - it should be equal to plotter that child is being removed from..
        /// </summary>
        public static string InvalidParentPlotterValueRemoving {
            get {
                return ResourceManager.GetString("InvalidParentPlotterValueRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data must be more detailized to build isolines..
        /// </summary>
        public static string IsolinesDataIsUndetailized {
            get {
                return ResourceManager.GetString("IsolinesDataIsUndetailized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source should be set before building isolines..
        /// </summary>
        public static string IsolinesDataSourceShouldBeSet {
            get {
                return ResourceManager.GetString("IsolinesDataSourceShouldBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible mistake: unsupported case in isoline building..
        /// </summary>
        public static string IsolinesUnsupportedCase {
            get {
                return ResourceManager.GetString("IsolinesUnsupportedCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not between values in corners..
        /// </summary>
        public static string IsolinesValueIsOutOfCell {
            get {
                return ResourceManager.GetString("IsolinesValueIsOutOfCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarithm base should be positive..
        /// </summary>
        public static string LogarithmBaseShouldBePositive {
            get {
                return ResourceManager.GetString("LogarithmBaseShouldBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of colors should be greater or equal to 2..
        /// </summary>
        public static string PaletteTooFewColors {
            get {
                return ResourceManager.GetString("PaletteTooFewColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter should be positive..
        /// </summary>
        public static string ParameterShouldBePositive {
            get {
                return ResourceManager.GetString("ParameterShouldBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child&apos;s parent plotter should be equal to null after it was removed from plotter..
        /// </summary>
        public static string ParentPlotterNotNull {
            get {
                return ResourceManager.GetString("ParentPlotterNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add item to Plotter - first it should be removed from another Plotter..
        /// </summary>
        public static string PlotterElementAddedToAnotherPlotter {
            get {
                return ResourceManager.GetString("PlotterElementAddedToAnotherPlotter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPlotterElement {0} did not removed all its contents from plotter&apos;s visual tree. Change this wrong behaviour in OnPlotterDetaching method of this IPlotterElement..
        /// </summary>
        public static string PlotterElementDidnotCleanedAfterItself {
            get {
                return ResourceManager.GetString("PlotterElementDidnotCleanedAfterItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plotter&apos;s MainHorizontalAxis should not be null..
        /// </summary>
        public static string PlotterMainHorizontalAxisShouldNotBeNull {
            get {
                return ResourceManager.GetString("PlotterMainHorizontalAxisShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plotter&apos;s MainVerticalAxis should not be null..
        /// </summary>
        public static string PlotterMainVerticalAxisShouldNotBeNull {
            get {
                return ResourceManager.GetString("PlotterMainVerticalAxisShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template should not be null to generate a marker..
        /// </summary>
        public static string TemplateShouldNotBeNull {
            get {
                return ResourceManager.GetString("TemplateShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text of tick returned by GetStringCore should not be null..
        /// </summary>
        public static string TextOfTickShouldNotBeNull {
            get {
                return ResourceManager.GetString("TextOfTickShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticks cannot be generated for this range..
        /// </summary>
        public static string UnsupportedRangeInAxis {
            get {
                return ResourceManager.GetString("UnsupportedRangeInAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical axis can be placed only from left or right..
        /// </summary>
        public static string VerticalAxisCannotBeHorizontal {
            get {
                return ResourceManager.GetString("VerticalAxisCannotBeHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong state of VisualBindings..
        /// </summary>
        public static string VisualBindingsWrongState {
            get {
                return ResourceManager.GetString("VisualBindingsWrongState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width and height cannot be negative..
        /// </summary>
        public static string WidthAndHeightCannotBeNegative {
            get {
                return ResourceManager.GetString("WidthAndHeightCannotBeNegative", resourceCulture);
            }
        }
    }
}
