# Custom workflow to build .NET Framework DLL
# Does a build, and will run tests in future after I write the tests, and will publish to nuget once I write that bit

name: Release to Nuget

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
    - name: Checkout DynamicDataDisplayReloaded
      uses: actions/checkout@v2.1.0

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
  
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: Restore NuGet Packages
      run: nuget restore sln\DynamicDataDisplay\DynamicDataDisplay.sln
      
    - name: Set Version
      run: sln\DynamicDataDisplay\PropertySheets\SetVersion.cmd ${{ github.event.release.tag_name }} >sln\DynamicDataDisplay\PropertySheets\BuildAssemblyInfo.cs
      
    - name: verify version in logs
      run: type sln\DynamicDataDisplay\PropertySheets\BuildAssemblyInfo.cs
      
    - name: Build Debug DLL
      run: msbuild sln\DynamicDataDisplay\DynamicDataDisplay.sln /p:Configuration=Debug

    - name: Build Release DLL
      run: msbuild sln\DynamicDataDisplay\DynamicDataDisplay.sln /p:Configuration=Release

    - name: Create DynamicDataDisplayReloaded nuget package
      run: nuget pack "src\DynamicDataDisplay\DynamicDataDisplay.csproj" -OutputDirectory Publish -properties "Configuration=Release;Platform=AnyCPU;OutputPath=..\..\sln\DynamicDataDisplay\Bin\Release_AnyCPU"     

    - name: Create DynamicDataDisplayReloaded.BitmapGraphs nuget package
      run: nuget pack "src\DynamicDataDisplay.BitmapGraphs\DynamicDataDisplay.BitmapGraphs.csproj" -OutputDirectory Publish -properties "Configuration=Release;Platform=AnyCPU;OutputPath=..\..\sln\DynamicDataDisplay\Bin\Release_AnyCPU"     

    - name: Create DynamicDataDisplayReloaded.Maps nuget package
      run: nuget pack "src\DynamicDataDisplay.Maps\DynamicDataDisplay.Maps.csproj" -OutputDirectory Publish -properties "Configuration=Release;Platform=AnyCPU;OutputPath=..\..\sln\DynamicDataDisplay\Bin\Release_AnyCPU"     

    - name: Create DynamicDataDisplayReloaded.Markers nuget package
      run: nuget pack "src\DynamicDataDisplay.Markers\DynamicDataDisplay.Markers.csproj" -OutputDirectory Publish -properties "Configuration=Release;Platform=AnyCPU;OutputPath=..\..\sln\DynamicDataDisplay\Bin\Release_AnyCPU"     

    - name: Create DynamicDataDisplayReloaded.RadioBand nuget package
      run: nuget pack "src\DynamicDataDisplay.RadioBand\DynamicDataDisplay.RadioBand.csproj" -OutputDirectory Publish -properties "Configuration=Release;Platform=AnyCPU;OutputPath=..\..\sln\DynamicDataDisplay\Bin\Release_AnyCPU"     

    - name: Create DynamicDataDisplayReloaded.SharpDX9 nuget package
      run: nuget pack "src\DynamicDataDisplay.SharpDX9\DynamicDataDisplay.SharpDX9.csproj" -OutputDirectory Publish -properties "Configuration=Release;Platform=AnyCPU;OutputPath=..\..\sln\DynamicDataDisplay\Bin\Release_AnyCPU"     

    - name: Publish Nuget Packages
      run: dotnet nuget push **/Publish/*.nupkg --api-key ${{ secrets.nuget_api_key }} --source https://api.nuget.org/v3/index.json --no-symbols true
